max_iterations: 10000
# snapshot_path: "E:/Left Atrial/output/"
snapshot_path: "/cabinet/yousef/Left Atrial/outputs/"
test_every_epochs: 20
dataset:
  train:
    params:
      # base_dir: "E:/Left Atrial/Left Atrial"
      base_dir: "/cabinet/dataset/Left Atrial"
      split: 'train'
      train_flod: 'train0.list'
  test:
    params:
      # base_dir: "E:/Left Atrial/Left Atrial"
      base_dir: "/cabinet/dataset/Left Atrial"
      split: 'test'
      test_flod: 'test0.list'
data_loader:
  train: 
    batch_size: 3
    shuffle: true
    num_workers: 0
    pin_memory: true
    # persistent_workers: true
training:
  optimizer:
    name: 'SGD'
    params:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    name: 'ReduceLROnPlateau'
    params:
        factor: 0.5
        patience: 5
        mode: 'min'
  epochs: 300
model: 
  name: 'MainModel_SGD_LA'
  params:
    # in_channels: 4
    # out_channels: 3
    # f_maps: 32


    spatial_shapes: [128, 128, 96]
    in_channels: 1
    out_channels: 2
                 
    # encoder params
    cnn_kernel_sizes: [7,5]
    cnn_features: [8,16]
    cnn_strides: [2,2]
    cnn_maxpools: [false, true]
    cnn_dropouts: 0.0
    hyb_kernel_sizes: [5,5,5]
    hyb_features: [32,64,128]
    hyb_strides: [2,2,2]
    hyb_maxpools: [true, true, true]
    hyb_cnn_dropouts: 0.0
    hyb_tf_proj_sizes: [32,64,64]
    hyb_tf_repeats: [2,2,1]
    hyb_tf_num_heads: [4,4,4]
    hyb_tf_dropouts: 0.15

    # decoder params
    dec_hyb_tcv_kernel_sizes: [7,7,7]
    dec_cnn_tcv_kernel_sizes: [7,7]
    
    dec_hyb_kernel_sizes: null
    dec_hyb_features: null
    dec_hyb_cnn_dropouts: null
    dec_hyb_tf_proj_sizes: null
    dec_hyb_tf_repeats: null
    dec_hyb_tf_num_heads: null
    dec_hyb_tf_dropouts: null
    dec_cnn_kernel_sizes: null
    dec_cnn_features: null
    dec_cnn_dropouts: null