datatype: 'Pancreas'
max_iterations: 6000
# snapshot_path: "E:/pancreas/output/"
snapshot_path: "/cabinet/yousef/pancreas/outputs/"
test_every_epochs: 20
dataset:
  train:
    params:
      # base_dir: "E:/pancreas/pancreas"
      base_dir: "/cabinet/dataset/pancreas"
      split: 'train'
      train_flod: 'train0.list'
  test:
    params:
      # base_dir: "E:/pancreas/pancreas"
      base_dir: "/cabinet/dataset/pancreas"
      split: 'test'
      test_flod: 'test0.list'
data_loader:
  train: 
    batch_size: 1
    shuffle: true
    num_workers: 14
    pin_memory: true
    persistent_workers: true
training:
  optimizer:
    name: 'SGD'
    params:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    name: 'ReduceLROnPlateau'
    params:
        factor: 0.5
        patience: 5
        mode: 'min'
  epochs: 300
model: 
  name: 'DLKA-Former_SGD_PANCREAS'
  params:
    in_channels: 1
    out_channels: 2
    img_size: [96, 96, 96]
    patch_size: [2,2,2]
    input_size: [110592, 13824,1728,216]
    do_ds: False