datatype: 'Pancreas'
max_iterations: 10000
# snapshot_path: "E:/pancreas/output/"
snapshot_path: "/cabinet/yousef/pancreas/outputs/"
test_every_epochs: 20
dataset:
  train:
    params:
      # base_dir: "E:/pancreas/pancreas"
      base_dir: "/cabinet/dataset/pancreas"
      split: 'train'
      train_flod: 'train0.list'
  test:
    params:
      # base_dir: "E:/pancreas/pancreas"
      base_dir: "/cabinet/dataset/pancreas"
      split: 'test'
      test_flod: 'test0.list'
data_loader:
  train: 
    batch_size: 2
    shuffle: true
    num_workers: 14
    pin_memory: true
    persistent_workers: true
training:
  optimizer:
    name: 'SGD'
    params:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    name: 'ReduceLROnPlateau'
    params:
        factor: 0.5
        patience: 5
        mode: 'min'
  epochs: 300
model: 
  name: 'lhUNET_SGD_PANCREAS_V7'
  params: # the class arguments defined above
    spatial_shapes: [96, 96, 96]
    do_ds: false # Deep Supervision
    in_channels: 1
    out_channels: 2
        
     # encoder params
    cnn_kernel_sizes: [5,3]
    cnn_features: [16,32]
    cnn_strides: [2,2]
    cnn_maxpools: [false, true]
    cnn_dropouts: 0.0
    cnn_blocks: nn # n: resunet, d: deformconv, b: basicunet
    hyb_kernel_sizes: [3,3,3]
    hyb_features: [32,64,128]
    hyb_strides: [2,2,2]
    hyb_maxpools: [false,false,false]
    hyb_cnn_dropouts: 0.0
    hyb_tf_proj_sizes: [32,64,128]
    hyb_tf_repeats: [1,1,1]
    hyb_tf_num_heads: [2,4,8]
    hyb_tf_dropouts: 0.15
    hyb_cnn_blocks: nnn # n: resunet, d: deformconv, b: basicunet
    hyb_vit_blocks: SSC # s: dlka_special_v2, S: dlka_sp_seq, c: dlka_channel_v2, C: dlka_ch_seq
    # hyb_vit_sandwich: false
    hyb_skip_mode: "cat" # "sum" or "cat"
    hyb_arch_mode: "collective" # sequential, residual, parallel, collective
    hyb_res_mode: "sum" # "sum" or "cat"

    # bridge 
    br_use: true
    br_skip_levels: [0,1,2,3]
    br_c_attn_use: true 
    br_s_att_use: true 
    br_m_att_use: true 
    br_use_p_ttn_w: true
                
    # decoder params
    dec_hyb_tcv_kernel_sizes: [5,5,5]
    dec_cnn_tcv_kernel_sizes: [5,7]
    dec_cnn_blocks: null
    dec_tcv_bias: false
    dec_hyb_tcv_bias: false
    dec_hyb_kernel_sizes: null
    dec_hyb_features: null
    dec_hyb_cnn_dropouts: null
    dec_hyb_tf_proj_sizes: null
    dec_hyb_tf_repeats: null
    dec_hyb_tf_num_heads: null
    dec_hyb_tf_dropouts: null
    dec_cnn_kernel_sizes: null
    dec_cnn_features: null
    dec_cnn_dropouts: null
    dec_hyb_cnn_blocks: null
    dec_hyb_vit_blocks: null
    # dec_hyb_vit_sandwich: null
    dec_hyb_skip_mode: null
    dec_hyb_arch_mode: "collective" # sequential, residual, parallel, collective, sequential-lite
    dec_hyb_res_mode: null
