datatype: 'LA'
max_iterations: 10000
# snapshot_path: "E:/Left Atrial/output/"
snapshot_path: "/cabinet/yousef/LA/outputs/"
test_every_epochs: 20
dataset:
  train:
    params:
      # base_dir: "E:/Left Atrial/Left Atrial"
      base_dir: "/cabinet/dataset/Left Atrial"
      split: 'train'
      train_flod: 'train0.list'
  test:
    params:
      # base_dir: "E:/Left Atrial/Left Atrial"
      base_dir: "/cabinet/dataset/Left Atrial"
      split: 'test'
      test_flod: 'test0.list'
data_loader:
  train: 
    batch_size: 1
    shuffle: true
    num_workers: 14
    pin_memory: true
    persistent_workers: true
training:
  optimizer:
    name: 'SGD'
    params:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    name: 'ReduceLROnPlateau'
    params:
        factor: 0.5
        patience: 5
        mode: 'min'
  epochs: 300
model: 
  name: 'SwinUNETR3D-v2_SGD_LA'
  params:
    img_size: [96,96,96]
    spatial_dims: 3
    in_channels: 1
    out_channels: 2
    use_v2: true