datatype: 'Pancreas'
max_iterations: 10000
# snapshot_path: "E:/pancreas/output/"
snapshot_path: "/cabinet/yousef/pancreas/outputs/"
test_every_epochs: 20
dataset:
  train:
    params:
      # base_dir: "E:/pancreas/pancreas"
      base_dir: "/cabinet/dataset/pancreas"
      split: 'train'
      train_flod: 'train0.list'
  test:
    params:
      # base_dir: "E:/pancreas/pancreas"
      base_dir: "/cabinet/dataset/pancreas"
      split: 'test'
      test_flod: 'test0.list'
data_loader:
  train: 
    batch_size: 2
    shuffle: true
    num_workers: 14
    pin_memory: true
    persistent_workers: true
training:
  optimizer:
    name: 'SGD'
    params:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    name: 'ReduceLROnPlateau'
    params:
        factor: 0.5
        patience: 5
        mode: 'min'
  epochs: 300
model: 
  name: 'UNETRPP3D_SGD_PANCREAS_batch_2'
  params:
    in_channels: 1
    out_channels: 2
    do_ds: false
    num_heads: 4
    dims: [32, 64, 128, 256]
    depths: [3, 3, 3, 3]